### ISSUE TITLE
Error messages coming in from API needs to be translated.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/oscommerce#20]
Right now even if I put front end to swedish, I get error messages in english.

**Comment by Boxedsolutions** [comment]
Its no good idea to do it before we could put country as iso code to Add payment. It will mess up the logic as it is right now.

If you have "Svenska" the API wants "Sverige" And if you have "English the api wants "Sweden", there is no good translation function for this in oscommerce. 

As discussed with @andyjohansson for a week ago at least, we discussed to make it possible to set the country by iso code instead of translated countryname.

**Comment by andyjohansson** [comment]
We are awaiting ISO Codes.

**Comment by joakim-combain** [comment]
I saw that Andreas sent in a support ticket yesterday about it so it will be fixed as soon as possible from our side. Leaving this open.

**Comment by Boxedsolutions** [comment]
Should be fixed.

**Comment by Boxedsolutions** [comment]
It shouldnt be possible to purchase with invoice from Norway.

**Comment by Boxedsolutions** [comment]
It should work, just set the language on first page and show the error messages in different countries
